CREATE DATABASE IF NOT EXISTS WORDPRESS;
CREATE USER IF NOT EXISTS 'hyungnoh'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON WORDPRESS.* TO 'hyungnoh'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';